name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get dotnet version info
      run: dotnet --info
    - name: Build with dotnet
      run: dotnet build ../Ingos.Api.sln --configuration Release
